In [1]:
import numpy as np
import pandas as pd

In [2]:
df_floor = pd.read_excel('use_data/침수관련_데이터.xlsx')
df_accident = pd.read_excel('use_data/교통사고_데이터.xlsx')

print(df_floor.shape, df_accident.shape)

(11500, 16) (11500, 5)

# 전처리

In [3]:
print(df_floor.info())
df_floor.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   자치구(구)            11500 non-null  object
 1   날짜                11500 non-null  int64
 2   1hr 최대 강수량(mm)    11500 non-null  float64
 3   일평균 강수량(mm)       11500 non-null  float64
 4   경사도(˚)            11500 non-null  float64
 5   해발고도(m)           11500 non-null  float64
 6   불투수면(%)           11500 non-null  float64
 7   녹지 면적율(%)         11500 non-null  float64
 8   하천 면적율(%)         11500 non-null  float64
 9   복개하천 개수(개)        11500 non-null  int64
 10  맨홀 개수(개)          11500 non-null  int64
 11  빗물받이 개수(개)        11500 non-null  int64
 12  빗물 펌프 개수(개)       11500 non-null  int64
 13  [AVG] 하수관로 비율(%)  11500 non-null  object
 14  [MAX] 하수관로 비율(%)  11500 non-null  object
 15  침수 피해(0/1)        11500 non-null  int64
dtypes: float64(7), int64(6), object(3)
memory usage: 1.4+ MB
None

,자치구(구),날짜,1hr 최대 강수량(mm),일평균 강수량(mm),경사도(˚),해발고도(m),불투수면(%),녹지 면적율(%),하천 면적율(%),복개하천 개수(개),맨홀 개수(개),빗물받이 개수(개),빗물 펌프 개수(개),[AVG] 하수관로 비율(%),[MAX] 하수관로 비율(%),침수 피해(0/1)
0,종로,20180601,0.0,0.0,12.033665,146.699945,0.42017,0.009418,0.011652,1,9854,16173,0,0.009084,0.033333,0
1,종로,20180602,0.0,0.0,12.033665,146.699945,0.42017,0.009418,0.011652,1,9854,16173,0,0.008864,0.033333,0
2,종로,20180603,0.0,0.0,12.033665,146.699945,0.42017,0.009418,0.011652,1,9854,16173,0,0.008182,0.033333,0
3,종로,20180604,0.0,0.0,12.033665,146.699945,0.42017,0.009418,0.011652,1,9854,16173,0,0.008745,0.033333,0
4,종로,20180605,0.0,0.0,12.033665,146.699945,0.42017,0.009418,0.011652,1,9854,16173,0,0.008753,0.033333,0

In [4]:
cols = ['자치구', '날짜', '1hr_최대강수량', '일평균강수량', '경사도', '해발고도', '불투수면',
       '녹지면적율', '하천면적율', '복개하천개수', '맨홀개수', '빗물받이개수',
       '빗물펌프개수', 'AVG_하수관로비율', 'MAX_하수관로비율', '침수피해']

df_floor.columns = cols

In [5]:
print(df_accident.info())
df_accident.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   자치구               11500 non-null  object
 1   날짜                11500 non-null  int64
 2   [AVG] 하수관로 비율(%)  11500 non-null  object
 3   [MAX] 하수관로 비율(%)  11500 non-null  object
 4   사고[건]             11500 non-null  int64
dtypes: int64(2), object(3)
memory usage: 449.3+ KB
None

  자치구        날짜 [AVG] 하수관로 비율(%) [MAX] 하수관로 비율(%)  사고[건]
0  종로  20180601         0.009084         0.033333      4
1  종로  20180602         0.008864         0.033333      4
2  종로  20180603         0.008182         0.033333      3
3  종로  20180604         0.008745         0.033333      2
4  종로  20180605         0.008753         0.033333      8

In [6]:
del df_floor['침수피해']

In [7]:
cols2 = ['자치구', '날짜', 'AVG_하수관로비율', 'MAX_하수관로비율', '사고건수']
df_accident.columns = cols2

In [8]:
df_floor['날짜'] = pd.to_datetime(df_floor['날짜'], format='%Y%m%d')
df_floor.loc[df_floor['AVG_하수관로비율'] == 'na', 'AVG_하수관로비율'] = np.NaN
df_floor.loc[df_floor['MAX_하수관로비율'] == 'na', 'MAX_하수관로비율'] = np.NaN

df_accident['날짜'] = pd.to_datetime(df_accident['날짜'], format='%Y%m%d')
df_accident.loc[df_accident['AVG_하수관로비율'] == 'na', 'AVG_하수관로비율'] = np.NaN
df_accident.loc[df_accident['MAX_하수관로비율'] == 'na', 'MAX_하수관로비율'] = np.NaN

In [9]:
df_floor['AVG_하수관로비율'] = df_floor['AVG_하수관로비율'].astype('float')
df_floor['MAX_하수관로비율'] = df_floor['MAX_하수관로비율'].astype('float')

df_accident['AVG_하수관로비율'] = df_accident['AVG_하수관로비율'].astype('float')
df_accident['MAX_하수관로비율'] = df_accident['MAX_하수관로비율'].astype('float')

In [10]:
df_floor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   자치구         11500 non-null  object
 1   날짜          11500 non-null  datetime64[ns]
 2   1hr_최대강수량   11500 non-null  float64
 3   일평균강수량      11500 non-null  float64
 4   경사도         11500 non-null  float64
 5   해발고도        11500 non-null  float64
 6   불투수면        11500 non-null  float64
 7   녹지면적율       11500 non-null  float64
 8   하천면적율       11500 non-null  float64
 9   복개하천개수      11500 non-null  int64
 10  맨홀개수        11500 non-null  int64
 11  빗물받이개수      11500 non-null  int64
 12  빗물펌프개수      11500 non-null  int64
 13  AVG_하수관로비율  11349 non-null  float64
 14  MAX_하수관로비율  11349 non-null  float64
dtypes: datetime64[ns](1), float64(9), int64(4), object(1)
memory usage: 1.3+ MB

In [11]:
df_accident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   자치구         11500 non-null  object
 1   날짜          11500 non-null  datetime64[ns]
 2   AVG_하수관로비율  11349 non-null  float64
 3   MAX_하수관로비율  11349 non-null  float64
 4   사고건수        11500 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 449.3+ KB

In [12]:
# null값 제거
df_floor = df_floor.dropna(axis=0, how='any')
df_accident = df_accident.dropna(axis=0, how='any')

In [13]:
print(df_floor.isna().sum(), '\n\n', df_accident.isna().sum())

자치구           0
날짜            0
1hr_최대강수량     0
일평균강수량        0
경사도           0
해발고도          0
불투수면          0
녹지면적율         0
하천면적율         0
복개하천개수        0
맨홀개수          0
빗물받이개수        0
빗물펌프개수        0
AVG_하수관로비율    0
MAX_하수관로비율    0
dtype: int64

 자치구           0
날짜            0
AVG_하수관로비율    0
MAX_하수관로비율    0
사고건수          0
dtype: int64

In [14]:
# df_floor['year'] = df_floor['날짜'].dt.year
df_floor['month'] = df_floor['날짜'].dt.month
df_floor['day'] = df_floor['날짜'].dt.day

# df_accident['year'] = df_accident['날짜'].dt.year
df_accident['month'] = df_accident['날짜'].dt.month
df_accident['day'] = df_accident['날짜'].dt.day

In [15]:
del df_floor['날짜']
del df_accident['날짜']

# 스케일링

In [16]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

col = ['1hr_최대강수량', '일평균강수량', '경사도', '해발고도', '불투수면', '녹지면적율', '하천면적율', '복개하천개수', 
          '맨홀개수', '빗물받이개수', '빗물펌프개수', 'AVG_하수관로비율', 'MAX_하수관로비율']

col2 = ['AVG_하수관로비율', 'MAX_하수관로비율', '사고건수']

stand_scale = StandardScaler()
minmax_scale = MinMaxScaler()
df_floor_standard = df_floor.copy()
df_floor_minmax = df_floor.copy()
df_accident_standard = df_accident.copy()
df_accident_minmax = df_accident.copy()

df_floor_standard[col] = stand_scale.fit_transform(df_floor_standard[col])
df_floor_minmax[col] = minmax_scale.fit_transform(df_floor_minmax[col])

df_accident_standard[col2] = stand_scale.fit_transform(df_accident_standard[col2])
df_accident_minmax[col2] = minmax_scale.fit_transform(df_accident_minmax[col2])

In [17]:
df_floor_minmax.head()

,자치구,1hr_최대강수량,일평균강수량,경사도,해발고도,불투수면,녹지면적율,하천면적율,복개하천개수,맨홀개수,빗물받이개수,빗물펌프개수,AVG_하수관로비율,MAX_하수관로비율,month,day
0,종로,0.0,0.0,0.883197,0.770065,0.15067,0.079188,0.026666,0.25,0.396268,0.219224,0.0,0.005219,0.000816,6,1
1,종로,0.0,0.0,0.883197,0.770065,0.15067,0.079188,0.026666,0.25,0.396268,0.219224,0.0,0.005093,0.000816,6,2
2,종로,0.0,0.0,0.883197,0.770065,0.15067,0.079188,0.026666,0.25,0.396268,0.219224,0.0,0.004701,0.000816,6,3
3,종로,0.0,0.0,0.883197,0.770065,0.15067,0.079188,0.026666,0.25,0.396268,0.219224,0.0,0.005025,0.000816,6,4
4,종로,0.0,0.0,0.883197,0.770065,0.15067,0.079188,0.026666,0.25,0.396268,0.219224,0.0,0.005029,0.000816,6,5

In [18]:
# One-Hot encoding
df_floor_onehot = pd.get_dummies(df_floor_minmax)
df_floor_onehot.head()

,1hr_최대강수량,일평균강수량,경사도,해발고도,불투수면,녹지면적율,하천면적율,복개하천개수,맨홀개수,빗물받이개수,...,자치구_성동,자치구_성북,자치구_송파,자치구_양천,자치구_영등포,자치구_용산,자치구_은평,자치구_종로,자치구_중,자치구_중랑
0,0.0,0.0,0.883197,0.770065,0.15067,0.079188,0.026666,0.25,0.396268,0.219224,...,False,False,False,False,False,False,False,True,False,False
1,0.0,0.0,0.883197,0.770065,0.15067,0.079188,0.026666,0.25,0.396268,0.219224,...,False,False,False,False,False,False,False,True,False,False
2,0.0,0.0,0.883197,0.770065,0.15067,0.079188,0.026666,0.25,0.396268,0.219224,...,False,False,False,False,False,False,False,True,False,False
3,0.0,0.0,0.883197,0.770065,0.15067,0.079188,0.026666,0.25,0.396268,0.219224,...,False,False,False,False,False,False,False,True,False,False
4,0.0,0.0,0.883197,0.770065,0.15067,0.079188,0.026666,0.25,0.396268,0.219224,...,False,False,False,False,False,False,False,True,False,False

In [19]:
# One-Hot encoding
df_accident_onehot = pd.get_dummies(df_accident_minmax)
df_accident_onehot.head()

,AVG_하수관로비율,MAX_하수관로비율,사고건수,month,day,자치구_강남,자치구_강동,자치구_강북,자치구_강서,자치구_관악,...,자치구_성동,자치구_성북,자치구_송파,자치구_양천,자치구_영등포,자치구_용산,자치구_은평,자치구_종로,자치구_중,자치구_중랑
0,0.005219,0.000816,0.166667,6,1,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,0.005093,0.000816,0.166667,6,2,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,0.004701,0.000816,0.125000,6,3,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,0.005025,0.000816,0.083333,6,4,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,0.005029,0.000816,0.333333,6,5,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [20]:
df_floor_label = df_floor_minmax.copy()
df_accident_label = df_accident_minmax.copy()
print(df_floor_minmax['자치구'].astype('category').cat.categories)
df_floor_label['자치구'] = df_floor_label['자치구'].astype('category').cat.codes
df_accident_label['자치구'] = df_accident_label['자치구'].astype('category').cat.codes

Index(['강남', '강동', '강북', '강서', '관악', '광진', '구로', '금천', '노원', '도봉', '동대문', '동작',
       '마포', '서대문', '서초', '성동', '성북', '송파', '양천', '영등포', '용산', '은평', '종로', '중',
       '중랑'],
      dtype='object')

# Modeling

## 침수 수위 예측(Regressor)

In [21]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [22]:
# 평가지표 함수 생성
def adjusted_r_squared(r2_score,X_test):
    	return 1 - (1-r2_score)*(len(X_test)-1)/(len(X_test)-X_test.shape[1]-1)

def regressor_metrics(y_test, y_pred):
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)
    print(f'MAE: {mae:.4f}')
    print(f'MSE: {mse:.4f}')
    print(f'RMSE: {rmse:.4f}')
    print(f'R2: {r2:.4f}')

In [23]:
# x, y 분리 함수 생성
def split_xy(df, encoding, target):
    from sklearn.model_selection import train_test_split
    if encoding == 'onehot':
        if target == 'avg':
            df_x = df.iloc[:, [i for i in range(len(df.columns)) if i not in (11, 12)]]
            df_y = df.iloc[:, 11]
            return df_x, df_y
        elif target == 'max':
            df_x = df.iloc[:, [i for i in range(len(df.columns)) if i not in (11, 12)]]
            df_y = df.iloc[:, 12]
            return df_x, df_y
        else:
            print('target is avg or max')
    elif encoding == 'label':
        if target == 'avg':
            df_x = df.iloc[:, [i for i in range(len(df.columns)) if i not in (12, 13)]]
            df_y = df.iloc[:, 12]
            return df_x, df_y
        elif target == 'max':
            df_x = df.iloc[:, [i for i in range(len(df.columns)) if i not in (12, 13)]]
            df_y = df.iloc[:, 13]
            return df_x, df_y
        else:
            print('target is avg or max')
    else:
        print('encoding is onehot or label')

### 모델 학습 수행

In [24]:
# 모델학습 함수 생성
# 주 타깃인 onehot - max를 기준으로 생성
def model_train(model):
    df_x, df_y = split_xy(df_floor_onehot, 'onehot', 'max')
    
    del df_x['경사도']
    del df_x['빗물받이개수']
    del df_x['일평균강수량']
    
    train_x, test_x, train_y, test_y = train_test_split(df_x, df_y, test_size=0.2, random_state=0, shuffle=True)

    model = model
    model.fit(train_x, train_y)
    predict_y = model.predict(test_x)
    regressor_metrics(test_y, predict_y)

In [25]:
from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor
print('RandomForestRegressor(random_state=0)')
model_train(RandomForestRegressor(random_state=0))
print('LGBMRegressor(random_state=0, force_col_wise=True)')
model_train(LGBMRegressor(random_state=0, force_col_wise=True))

RandomForestRegressor(random_state=0)
MAE: 0.0045
MSE: 0.0004
RMSE: 0.0198
R2: 0.3360
LGBMRegressor(random_state=0, force_col_wise=True)
[LightGBM] [Info] Total Bins 579
[LightGBM] [Info] Number of data points in the train set: 9079, number of used features: 35
[LightGBM] [Info] Start training from score 0.010093
MAE: 0.0057
MSE: 0.0004
RMSE: 0.0197
R2: 0.3430

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
print('LinearRegression()')
model_train(LinearRegression())
print('Lasso()')
model_train(Lasso())

LinearRegression()
MAE: 0.0073
MSE: 0.0006
RMSE: 0.0235
R2: 0.0663
Lasso()
MAE: 0.0083
MSE: 0.0006
RMSE: 0.0244
R2: -0.0001

In [27]:
print('Lasso(alpha=0.0001)')
model_train(Lasso(alpha=0.0001))
print('Lasso(alpha=10)')
model_train(Lasso(alpha=10))

Lasso(alpha=0.0001)
MAE: 0.0074
MSE: 0.0006
RMSE: 0.0236
R2: 0.0639
Lasso(alpha=10)
MAE: 0.0083
MSE: 0.0006
RMSE: 0.0244
R2: -0.0001

In [28]:
from sklearn.linear_model import ElasticNet
print('ElasticNet')
model_train(ElasticNet())

ElasticNet
MAE: 0.0083
MSE: 0.0006
RMSE: 0.0244
R2: -0.0001

### GridSearchCV

In [30]:
from sklearn.model_selection import GridSearchCV

param_lgb = {
    "learning_rate" : [0.01, 0.1, 0.2, 0.3, 0.5],
    # "max_depth" : [25, 50, 75],
    "num_leaves" : [300,500,900,1200],
    "n_estimators" : [200, 300, 500, 800],
}

df_x, df_y = split_xy(df_floor_onehot, 'onehot', 'max')

del df_x['경사도']
del df_x['빗물받이개수']
del df_x['일평균강수량']

train_x, test_x, train_y, test_y = train_test_split(df_x, df_y, test_size=0.2, random_state=0, shuffle=True)

gs_lb = GridSearchCV(LGBMRegressor(random_state=0, n_jobs=-1, force_col_wise=True, verbose=-1), param_grid=param_lgb, cv=3)
gs_lb.fit(train_x, train_y)

GridSearchCV(cv=3,
             estimator=LGBMRegressor(force_col_wise=True, n_jobs=-1,
                                     random_state=0, verbose=-1),
             param_grid={'learning_rate': [0.01, 0.1, 0.2, 0.3, 0.5],
                         'n_estimators': [200, 300, 500, 800],
                         'num_leaves': [300, 500, 900, 1200]})

In [31]:
# best parameter 반환
gs_lb.best_params_

{'learning_rate': 0.01, 'n_estimators': 300, 'num_leaves': 300}

In [32]:
# best parameter로 예측
pred = gs_lb.predict(test_x)

In [33]:
# 평가지표 확인
regressor_metrics(test_y, pred)

MAE: 0.0050
MSE: 0.0004
RMSE: 0.0197
R2: 0.3429

In [34]:
def gridsearchcv_model(model, params, cvs=3):
    from sklearn.model_selection import GridSearchCV
    df_x, df_y = split_xy(df_floor_onehot, 'onehot', 'max')
    
    del df_x['경사도']
    del df_x['빗물받이개수']
    del df_x['일평균강수량']
    
    train_x, test_x, train_y, test_y = train_test_split(df_x, df_y, test_size=0.2, random_state=0, shuffle=True)
    
    gs = GridSearchCV(model, param_grid=params, cv=cvs)
    gs.fit(train_x, train_y)
    
    print(f'best_params: {gs.best_params_}')
    
    pred = gs.predict(test_x)
    regressor_metrics(test_y, pred)
    
    return gs

In [35]:
from sklearn.ensemble import RandomForestRegressor
param_rfr = {
    "max_depth" : [25, 50, 75], # 과적합 방지
    "n_estimators" : [200, 300, 500, 800],
    "min_samples_split":[2, 3, 5, 8],
    "min_samples_leaf":[1, 2, 3, 5, 8]
}

gs_rf = gridsearchcv_model(RandomForestRegressor(random_state=0, n_jobs=-1), param_rfr)

best_params: {'max_depth': 50, 'min_samples_leaf': 8, 'min_samples_split': 3, 'n_estimators': 200}
MAE: 0.0048
MSE: 0.0004
RMSE: 0.0202
R2: 0.3124